name: simple_note_taking_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.2
  flutter_bloc: ^8.1.3
  hydrated_bloc: ^9.1.3
  shared_preferences: ^2.2.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  equatable: ^2.0.5
  uuid: ^4.1.0
  

  


dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
